---

- name: Configure laptop
  gather_facts: true
  hosts: localhost
  connection: local
  tasks:

    - name: Display the config
      debug:
        msg: "The hostname is {{ ansible_hostname }} and the OS is {{ ansible_os_family }}"

    - name: Update apt cache
      apt:
        update_cache: yes
      become: true

    - name: Include geerlingguy.docker role
      include_role:
        name: geerlingguy.docker
        apply:
          become: true

    - name: Include dotfiles role
      include_role:
        name: dotfiles

    - name: Include zsh role
      include_role:
        name: zsh

    - name: Include pyenv role
      include_role:
        name: pyenv

    - name: Include rbenv role
      include_role:
        name: rbenv

    - name: nvm
      shell: >
        curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash
      args:
        creates: "{{ ansible_env.HOME }}/.nvm/nvm.sh"
